const auditorium = new Auditorium([
  {
    rows: boxMap,
    name: "Box left 1.",
    mirrored: false,
    vert: 25,
    hor: 15,
    angle: 90,
  },
  {
    rows: boxMap,
    name: "Box left 2.",
    mirrored: false,
    vert: 40,
    hor: 15,
    angle: 90,
  },
  {
    rows: boxMap,
    name: "Box left 3.",
    mirrored: false,
    vert: 55,
    hor: 15,
    angle: 90,
  },
  {
    rows: sideBalconyMap,
    name: "Balcony left",
    mirrored: false,
    vert: 75,
    hor: 20,
    angle: 60,
  },
  {
    rows: boxMap,
    name: "Box right 1.",
    mirrored: true,
    vert: 25,
    hor: 85,
    angle: -90,
  },
  {
    rows: boxMap,
    name: "Box right 2.",
    mirrored: true,
    vert: 40,
    hor: 85,
    angle: -90,
  },
  {
    rows: boxMap,
    name: "Box right 3.",
    mirrored: true,
    vert: 55,
    hor: 85,
    angle: -90,
  },
  {
    rows: sideBalconyMap,
    name: "Balcony right",
    mirrored: true,
    vert: 75,
    hor: 80,
    angle: -60,
  },
  {
    rows: midBalconyMap,
    name: "Balcony mid.",
    mirrored: false,
    vert: 85,
    hor: 50,
  },
  {
    rows: centralAuditorium,
    name: "Auditorium",
    mirrored: false,
    vert: 50,
    hor: 50,
  },
]);
auditorium.render("app");
